// Generated by rstantools.  Do not edit by hand.

/*
    RNAFracQuant is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    RNAFracQuant is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with RNAFracQuant.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.19.1
#include <stan/model/model_header.hpp>
namespace model_RNAFracQuant_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_RNAFracQuant");
    reader.add_event(34, 32, "end", "model_RNAFracQuant");
    return reader;
}
#include <stan_meta_header.hpp>
class model_RNAFracQuant : public prob_grad {
private:
        int n;
        std::vector<int> Tot;
        std::vector<int> Sup;
        std::vector<int> Pellet;
public:
    model_RNAFracQuant(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_RNAFracQuant(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_RNAFracQuant_namespace::model_RNAFracQuant";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 3;
            context__.validate_dims("data initialization", "n", "int", context__.to_vec());
            n = int(0);
            vals_i__ = context__.vals_i("n");
            pos__ = 0;
            n = vals_i__[pos__++];
            check_greater_or_equal(function__, "n", n, 1);
            current_statement_begin__ = 7;
            validate_non_negative_index("Tot", "n", n);
            context__.validate_dims("data initialization", "Tot", "int", context__.to_vec(n));
            Tot = std::vector<int>(n, int(0));
            vals_i__ = context__.vals_i("Tot");
            pos__ = 0;
            size_t Tot_k_0_max__ = n;
            for (size_t k_0__ = 0; k_0__ < Tot_k_0_max__; ++k_0__) {
                Tot[k_0__] = vals_i__[pos__++];
            }
            size_t Tot_i_0_max__ = n;
            for (size_t i_0__ = 0; i_0__ < Tot_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "Tot[i_0__]", Tot[i_0__], 0);
            }
            current_statement_begin__ = 8;
            validate_non_negative_index("Sup", "n", n);
            context__.validate_dims("data initialization", "Sup", "int", context__.to_vec(n));
            Sup = std::vector<int>(n, int(0));
            vals_i__ = context__.vals_i("Sup");
            pos__ = 0;
            size_t Sup_k_0_max__ = n;
            for (size_t k_0__ = 0; k_0__ < Sup_k_0_max__; ++k_0__) {
                Sup[k_0__] = vals_i__[pos__++];
            }
            size_t Sup_i_0_max__ = n;
            for (size_t i_0__ = 0; i_0__ < Sup_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "Sup[i_0__]", Sup[i_0__], 0);
            }
            current_statement_begin__ = 9;
            validate_non_negative_index("Pellet", "n", n);
            context__.validate_dims("data initialization", "Pellet", "int", context__.to_vec(n));
            Pellet = std::vector<int>(n, int(0));
            vals_i__ = context__.vals_i("Pellet");
            pos__ = 0;
            size_t Pellet_k_0_max__ = n;
            for (size_t k_0__ = 0; k_0__ < Pellet_k_0_max__; ++k_0__) {
                Pellet[k_0__] = vals_i__[pos__++];
            }
            size_t Pellet_i_0_max__ = n;
            for (size_t i_0__ = 0; i_0__ < Pellet_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "Pellet[i_0__]", Pellet[i_0__], 0);
            }
            // initialize transformed data variables
            // execute transformed data statements
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 14;
            num_params_r__ += 1;
            current_statement_begin__ = 15;
            num_params_r__ += 1;
            current_statement_begin__ = 18;
            num_params_r__ += 1;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_RNAFracQuant() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 14;
        if (!(context__.contains_r("scaling_factor_sup")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable scaling_factor_sup missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("scaling_factor_sup");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "scaling_factor_sup", "double", context__.to_vec());
        double scaling_factor_sup(0);
        scaling_factor_sup = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, scaling_factor_sup);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable scaling_factor_sup: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 15;
        if (!(context__.contains_r("scaling_factor_pellet")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable scaling_factor_pellet missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("scaling_factor_pellet");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "scaling_factor_pellet", "double", context__.to_vec());
        double scaling_factor_pellet(0);
        scaling_factor_pellet = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, scaling_factor_pellet);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable scaling_factor_pellet: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 18;
        if (!(context__.contains_r("phi")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable phi missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("phi");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "phi", "double", context__.to_vec());
        double phi(0);
        phi = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(phi);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable phi: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 14;
            local_scalar_t__ scaling_factor_sup;
            (void) scaling_factor_sup;  // dummy to suppress unused var warning
            if (jacobian__)
                scaling_factor_sup = in__.scalar_lb_constrain(0, lp__);
            else
                scaling_factor_sup = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 15;
            local_scalar_t__ scaling_factor_pellet;
            (void) scaling_factor_pellet;  // dummy to suppress unused var warning
            if (jacobian__)
                scaling_factor_pellet = in__.scalar_lb_constrain(0, lp__);
            else
                scaling_factor_pellet = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 18;
            local_scalar_t__ phi;
            (void) phi;  // dummy to suppress unused var warning
            if (jacobian__)
                phi = in__.scalar_constrain(lp__);
            else
                phi = in__.scalar_constrain();
            // model body
            current_statement_begin__ = 22;
            lp_accum__.add(gamma_log<propto__>(scaling_factor_sup, 1, 1));
            current_statement_begin__ = 23;
            lp_accum__.add(gamma_log<propto__>(scaling_factor_pellet, 1, 1));
            current_statement_begin__ = 25;
            lp_accum__.add(cauchy_log<propto__>(phi, 0, 3));
            current_statement_begin__ = 27;
            for (int idx = 1; idx <= n; ++idx) {
                current_statement_begin__ = 30;
                lp_accum__.add(neg_binomial_2_log<propto__>(get_base1(Tot, idx, "Tot", 1), ((scaling_factor_sup * get_base1(Sup, idx, "Sup", 1)) + (scaling_factor_pellet * get_base1(Pellet, idx, "Pellet", 1))), phi));
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("scaling_factor_sup");
        names__.push_back("scaling_factor_pellet");
        names__.push_back("phi");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_RNAFracQuant_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        double scaling_factor_sup = in__.scalar_lb_constrain(0);
        vars__.push_back(scaling_factor_sup);
        double scaling_factor_pellet = in__.scalar_lb_constrain(0);
        vars__.push_back(scaling_factor_pellet);
        double phi = in__.scalar_constrain();
        vars__.push_back(phi);
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            if (!include_gqs__ && !include_tparams__) return;
            if (!include_gqs__) return;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    static std::string model_name() {
        return "model_RNAFracQuant";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "scaling_factor_sup";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "scaling_factor_pellet";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "phi";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
        }
        if (!include_gqs__) return;
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "scaling_factor_sup";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "scaling_factor_pellet";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "phi";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
        }
        if (!include_gqs__) return;
    }
}; // model
}  // namespace
typedef model_RNAFracQuant_namespace::model_RNAFracQuant stan_model;
#endif
